name: Docker Build/Publish Image 
on:  
  workflow_dispatch:
    inputs:
      arch:
        description: 'Architectures'
        required: true
        default: 'linux/arm/v7,linux/amd64'
env:
  IMAGE_VERSION: 1.0.${{ github.run_number }}

jobs:   
  build:    
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1    

    - name: Login in to registry
      uses: docker/login-action@v1.6.0
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to registry
      uses: docker/build-push-action@v2.2.0
      with:
        push: true
        platforms: ${{ github.event.inputs.arch }}
          # tags: <org-name>/<repo-name>/<app-name>:${{ env.IMAGE_TAG }}
        tags: |
          ghcr.io/${{ github.repository }}:${{ env.IMAGE_VERSION }}
          ghcr.io/${{ github.repository }}:latest
          
